version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  sonarcloud: sonarsource/sonarcloud@1.0.0

jobs:
  sonar_scan:
    docker:
      - image: 'circleci/openjdk:11.0.8-jdk'
    steps:
    - checkout
    - sonarcloud/scan

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - sonar_scan:
          context: SonarCloud # this context has an environmental variable set containing key